/// English localization strings for NestMate
class AppLocalizationsEn {
  static const Map<String, String> translations = {
    // Onboarding
    'language': 'Language',
    'selectLanguage': 'Select Language',
    'english': 'English',
    'hindi': 'Hindi',
    'telugu': 'Telugu',
    'continueButton': 'Continue',
    'next': 'Next',
    'back': 'Back',
    'fieldRequired': 'This field is required',
    'enterValidAmount': 'Enter a valid amount',
    'welcome': 'NestMate',
    'tagline': 'Making community living easy.',
    'welcomeSubtitle':
        "Maintenance made simple. Log in with a one-time code on your phone, or with a password if you've set one.",
    'getStarted': 'Get Started',
    'clearMonthlyBills': 'Clear monthly bills',
    'seeExactlyWhatYouOwe': 'See exactly what you owe and why',
    'payInSeconds': 'Pay in seconds',
    'upiPaymentUploadProof': 'Pay via UPI in one tap, then upload your receipt to confirm.',
    'fairWaterBilling': 'Fair water billing',
    'chargedByActualUsage': 'Priced by how much water you use, from one fair shared rate — never split evenly across flats.',

    // Authentication
    'login': 'Login',
    'signup': 'Sign Up',
    'loginWithPhone': 'Login with Phone Number',
    'loginWithPassword': 'Login with Password',
    'loginWithOtp': 'Login with OTP',
    'signInHeading': 'Sign in',
    'residentLoginSub': 'Sign in to view your bills and community updates.',
    'adminLoginSub': 'Sign in to manage your building, billing, and residents.',
    'phoneNumber': 'Phone Number',
    'enterPhoneNumber': 'Please enter your phone number',
    'password': 'Password',
    'enterPassword': 'Please enter your password',
    'incorrectPassword': 'Incorrect password. Try "Login with OTP" instead.',
    'showPassword': 'Show password',
    'hidePassword': 'Hide password',
    'confirmPassword': 'Confirm Password',
    'flatNumber': 'Flat Number',
    'enterFlatNumber': 'Please enter your flat number',
    'name': 'Name',
    'enterYourName': 'Enter your full name',
    'enterOtp': 'Enter 6-digit OTP',
    'verifyPhoneNumber': 'Verify Your Phone Number',
    'otpSentMessage': 'We\'ve sent a 6-digit code to your phone',
    'resendOtp': 'Resend OTP',
    'resendOtpIn': 'Resend OTP in ',
    'seconds': ' seconds',
    'forgotPassword': 'Forgot Password?',
    'passwordReset': 'Password Reset',
    'createAccount': 'Create Account',
    'haveAccount': 'Already have an account?',
    'noAccount': 'Don\'t have an account?',
    'agreeToTermsAndConditions': 'I agree to Terms & Conditions',
    'agreeToTerms': 'Please agree to terms and conditions',
    'passwordMinimumLength': 'Password must be at least 6 characters',
    'passwordMismatch': 'Passwords do not match',
    'joinNestMate': 'Join NestMate',
    'createAdminAccount': 'Create admin account',
    'adminSignupSub': 'Set up your name, phone, and password — you\'ll register your building next.',
    'enterName': 'Please enter your name',
    'fillDetailsBelow': 'Please fill in your details below',
    'enterCredentials': 'Enter your phone number and password',
    'accountCreatedSuccessfully': 'Account created successfully!',
    'verify': 'Verify',
    'or': 'OR',

    // Common
    'save': 'Save',
    'submit': 'Submit',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'edit': 'Edit',
    'close': 'Close',
    'loading': 'Loading...',
    'error': 'Error',
    'success': 'Success',
    'warning': 'Warning',
    'confirm': 'Confirm',
    'ok': 'OK',
    'yes': 'Yes',
    'no': 'No',
    'invalidInput': 'Invalid input. Please check your entries.',
    'networkError': 'Network error. Please check your connection.',

    // Resident
    'resident': 'Resident',
    'residents': 'Residents',
    'home': 'Home',
    'residentName': 'Resident Name',
    'profile': 'Profile',
    'billing': 'Billing',
    'payment': 'Payment',
    'bills': 'Bills',
    'pastBills': 'Past Bills',
    'amountDue': 'Amount Due',
    'billBreakdown': 'Bill Breakdown',
    'seeHowItsCalculated': 'See how it\'s calculated',
    'waterUsage': 'Water Usage',
    'waterMeter': 'Water Meter',
    'startReading': 'Start',
    'endReading': 'End',
    'usage': 'Usage',
    'yourUsageThisMonth': 'Your usage this month',
    'viewMeterPhoto': 'View meter photo',
    'waterTankerShare': 'Water tanker share',
    'commonMaintenance': 'Common maintenance',
    'subtotal': 'Subtotal',
    'downloadStatement': 'Download statement',
    'commonShare': 'Common Share',
    'credits': 'Credits',
    'openingBalance': 'Opening Balance',
    'pay': 'Pay Now',
    'paymentStatus': 'Payment Status',
    'uploadScreenshot': 'Upload Screenshot',
    'screenshotUploaded': 'Screenshot Uploaded',
    'replaceScreenshotBtn': 'Replace screenshot',
    'paymentConfirmed': 'Payment Confirmed',
    'paymentConfirmedByAdminLabel': 'Payment confirmed by admin',
    'reportIssue': 'Report Issue',
    'communityNotices': 'Community Notices',
    'postNoticeSub': 'Post to everyone in the building',
    'joinCommunity': 'Join Community',
    'logout': 'Logout',
    'confirmLogout': 'Are you sure you want to logout?',
    'total': 'Total',
    'featureComingSoon': 'This feature is coming soon!',
    'paymentFeatureComingSoon': 'Payment features coming soon',

    // Admin
    'admin': 'Admin',
    'community': 'Community',
    'communities': 'Communities',
    'settings': 'Settings',
    'management': 'Management',
    'dashboard': 'Dashboard',
    'flats': 'Flats',
    'addFlat': 'Add Flat',
    'editFlat': 'Edit Flat',
    'flat': 'Flat',
    'totalFlats': 'Total Flats',
    'totalResidents': 'Total Residents',
    'addResident': 'Add Resident',
    'editResident': 'Edit Resident',
    'manageFlats': 'Manage Flats',
    'manageResidents': 'Manage Residents',
    'expenses': 'Expenses',
    'addExpense': 'Add Expense',
    'waterCalculation': 'Water Calculation',
    'calculateBills': 'Calculate Bills',
    'generateBills': 'Generate Bills',
    'confirmPayments': 'Confirm Payments',
    'billsPending': 'Bills Pending',
    'paymentsVerifying': 'Payments Verifying',
    'outstandingAmount': 'Outstanding Amount',
    'collectionStatus': 'Collection Status',
    'paid': 'Paid',
    'pending': 'Pending',
    'collected': 'Collected',
    'addAdvance': 'Add Advance',
    'advances': 'Advances',

    // Units
    'rupees': '₹',
    'litres': 'L',

    // Messages
    'successfullySaved': 'Successfully saved!',
    'successfullyDeleted': 'Successfully deleted!',
    'errorOccurred': 'An error occurred. Please try again.',
    'phoneAlreadyExists': 'This phone number is already registered.',
    'flatNotFound': 'Flat not found.',
    'flatPhoneMismatch':
        "That phone number doesn't match our records for this flat. Contact your admin.",
    'adminAlreadyExists':
        'This building already has an admin. Ask them to add you as a flat, or request a handoff.',
    'invalidOtp': 'Invalid OTP. Please try again.',
    'otpSendFailed': "Couldn't send the OTP. Please try again.",
    'otpSent': 'OTP sent to your phone number.',

    // Resident shell / nav
    'navBuilding': 'Building',
    'navCommunity': 'Community',
    'navProfile': 'Profile',

    // Community feed
    'communitySub': 'Association updates',
    'committee': 'Association Committee',
    'pinned': 'Pinned',
    'writeComment': 'Write a comment…',
    'comment': 'Comment',
    'comments': 'comments',
    'react': 'React',
    'notJoinedCommunity': 'Not in an association',
    'communityLocked': 'Join an association to see community updates',

    // Profile
    'yourFlat': 'Your flat',
    'totalPaidSoFar': 'Paid so far',
    'changePhoto': 'Change photo',
    'associationRow': 'Association',
    'joinedTo': 'Part of',
    'leaveAssociation': 'Leave association',

    // Personal Expenses
    'myPersonalExpensesCard': 'My Personal Expenses',
    'personalExpenses': 'Personal Expenses',
    'addPersonalExpense': 'Add Expense',
    'totalSpentLabel': 'Total spent',
    'spendingByCategoryLabel': 'Spending by category',
    'noPersonalExpensesTitle': 'No personal expenses yet',
    'noPersonalExpensesSub': 'Track your own spending — separate from the building\'s finances.',
    'expenseDateLabel': 'Date',
    'categoryFood': 'Food',
    'categoryTransport': 'Transport',
    'categoryShopping': 'Shopping',
    'categoryBills': 'Bills',
    'categoryHealth': 'Health',
    'categoryEntertainment': 'Entertainment',
    'categoryOther': 'Other',

    // Pay Now
    'payTo': 'Pay to',
    'copyId': 'Copy ID',
    'openUpiApp': 'Open UPI app',
    'noUpiAppFound': 'No UPI app found on this device',
    'afterPayUploadScreenshot': 'After paying, upload your screenshot',
    'notPaidYet': 'Not paid yet',

    // Report Issue
    'whatIssue': "What's the issue?",
    'issueType': 'Type',
    'selectIssueType': 'Select a type',
    'whereLocation': 'Where',
    'addPhoto': 'Add photo',
    'takePhoto': 'Take photo',
    'chooseFromGallery': 'Choose from gallery',
    'removePhoto': 'Remove photo',
    'photoPickFailed': "Couldn't open the camera or gallery.",
    'myIssues': 'My issues',
    'inProgress': 'In progress',
    'resolved': 'Resolved',
    'issueDetails': 'Issue details',
    'submittedOn': 'Submitted on',
    'photoAttached': 'Photo attached',
    'issueSubmitted': 'Issue submitted',

    // Admin: block setup
    'newBlockTitle': 'Create your block',
    'newBlockSub':
        'First time here — name your block and set where residents will pay.',
    'blockNameLabel': 'Block name',
    'upiIdLabel': 'Collection UPI ID',
    'yourNameInCharge': 'Your name (in-charge)',
    'createBlockBtn': 'Continue',
    'addBuildingPhoto': 'Add building photo',
    'collectorNameLabel': 'Collector name (who receives payments)',
    'waterMeteredLabel': 'This building bills water by usage (metered)',
    'committeeEnabledLabel': 'Allow a read-only committee member',
    'joinCodeLabel': 'Resident join code',

    // Admin: add flats & residents
    'addFlatsResidents': 'Add flats & residents',
    'addPeopleSub':
        "Add each flat and the resident's phone. They log in with that number.",
    'residentNameLabel': 'Resident name',
    'tankerExemptLabel': 'No water tanker (exempt)',
    'addFlatBtn': 'Add flat',
    'goToDashboard': 'Go to dashboard',
    'emptyFlatsTitle': 'No flats added yet',
    'emptyFlatsSub': 'Add your first flat to get started.',
    'exemptTag': 'Exempt',

    // Admin: join association
    'joinAssociationTitle': 'Join an association',
    'joinSub':
        "Is your building part of a residents' association? Enter the code they shared to connect.",
    'associationCodeLabel': 'Association code',
    'joinBtn': 'Join association',
    'joinedLabel': 'Joined',
    'notJoinedLabel': 'Not in an association',

    // Admin: expenses
    'monthExpenses': "This month's expenses",
    'emptyExpensesTitle': 'No expenses yet',
    'emptyExpensesSub':
        "Add this month's costs — tanker, salary, diesel — and the app splits them across flats.",
    'addFirstExpense': 'Add first expense',
    'frontedBy': 'fronted by',
    'recoverFrom': 'recover from',
    'generateBillsBtn': 'Generate bills',

    // Admin: add expense
    'expenseNameLabel': 'What was it for',
    'categoryLabel': 'Category',
    'specifyCategoryHint': 'Please specify',
    'amountLabel': 'Amount',
    'splitAcross': 'Split across',
    'allFlatsOption': 'All flats',
    'specificFlatsOption': 'Choose specific flats',
    'whoPaidThis': 'Who paid this?',
    'paidToCollector': 'Paid to collector (normal)',
    'residentFrontedIt': 'A resident paid it directly',
    'whichFlatFronted': 'Which flat fronted it?',
    'addReceiptOptional': 'Add receipt photo (optional)',
    'saveExpenseBtn': 'Save expense',

    // Admin: add advance
    'advanceReasonLabel': 'Reason',
    'advanceGivenTo': 'Advance given to',
    'recoverFromRows': 'Recover from (flat : amount)',
    'addAnotherFlat': 'Add another flat',
    'saveAdvanceBtn': 'Save advance',

    // Admin: water calculator
    'waterCalcSub':
        "Enter meter readings & costs — the app works out each flat's share by usage.",
    'blendedRate': 'Blended rate',
    'perThousandLitres': 'per 1,000 L',
    'totalUsage': 'Total usage',
    'totalWaterCost': 'Total water cost',
    'numberOfTankers': 'Number of tankers',
    'costPerTanker': 'Cost per tanker',
    'meterReadingsHeader': 'Meter readings',
    'initialReading': 'Initial',
    'finalReading': 'Final',
    'addToBills': 'Add to bills',

    // Admin: generate bills
    'previewBills': 'Preview bills',
    'totalSpend': 'Total spend',
    'billsReadyCount': 'bills ready',
    'sendToResidents': 'Send to residents',
    'sendViaWhatsApp': 'Send via WhatsApp',
    'whatsAppOpenFailed': "Couldn't open WhatsApp. Make sure it's installed.",
    'sendViaSms': 'Send via SMS',
    'smsOpenFailed': "Couldn't open the Messages app.",
    'shareGroupSummary': 'Share month summary with the group',
    'shareGroupSummarySub': "One message with this month's expense breakdown, for your building's own group chat.",
    'copyMessageLabel': 'Copy message',
    'copiedToClipboard': 'Copied to clipboard',
    'billsGeneratedLabel': 'Bills generated',
    'refreshBillsBtn': 'Refresh bills (adds any new flats)',
    'billingMonthLabel': 'Billing month',
    'selectBillingMonth': 'Select billing month',

    // Admin: confirm payments
    'confirmBtn': 'Confirm',
    'awaitingConfirmationLabel': 'Awaiting confirmation',
    'confirmedTabLabel': 'Confirmed',
    'confirmedOnLabel': 'Confirmed',
    'noConfirmedPaymentsTitle': 'No confirmed payments yet',
    'noConfirmedPaymentsSub': 'Payments you confirm this month will show up here.',
    'notifications': 'Notifications',
    'openIssuesLabel': 'Open issues',
    'noNotificationsTitle': "You're all caught up",
    'noNotificationsSub': 'No pending payment confirmations or open issues right now.',
    'noPaymentsPendingTitle': "You're all caught up",
    'noPaymentsPendingSub': 'No payments are waiting for confirmation right now.',
    'viewScreenshotLabel': 'View payment screenshot',
    'justNow': 'Just now',
    'minutesAgoSuffix': 'min ago',
    'hoursAgoSuffix': 'hr ago',
    'daysAgoSuffix': 'd ago',

    // Admin: flats management
    'flatsResidentsTitle': 'Flats & residents',

    // Admin: transfer admin role
    'transferAdminRole': 'Transfer admin role',
    'transferAdminTitle': 'Hand off the admin role',
    'transferAdminSub':
        'Only one person can be admin for this building at a time. Enter the phone number of who should take over — you will be signed out once the handoff is done.',
    'newAdminPhoneLabel': "New admin's phone number",
    'transferAdminBtn': 'Transfer admin role',
    'transferAdminConfirmTitle': 'Transfer admin role?',
    'transferAdminConfirmBody':
        "You'll immediately lose admin access, and this phone number will be able to manage the building instead. This can't be undone from here.",
    'transferAdminSuccess': 'Admin role transferred. Signing you out…',

    // Misc
    'dueBy': 'Due',
    'earlierMonths': 'Earlier months',
    'noEarlierMonthsYet': 'No earlier months yet — this is the first billing month for this building.',
    'continueAsCommitteeLink': 'Continue as committee member (read-only)',
    'billNotReadyTitle': "This month's bill isn't ready yet",
    'billNotReadySub': "Your admin hasn't generated this month's bills yet. Check back once they do.",
  };

  static String get(String key, {String defaultValue = ''}) {
    return translations[key] ?? defaultValue;
  }
}
