/// Hindi localization strings for NestMate
class AppLocalizationsHi {
  static const Map<String, String> translations = {
    // Onboarding
    'language': 'भाषा',
    'selectLanguage': 'भाषा चुनें',
    'english': 'अंग्रेज़ी',
    'hindi': 'हिन्दी',
    'telugu': 'तेलुगु',
    'continueButton': 'जारी रखें',
    'next': 'अगला',
    'back': 'वापस',
    'fieldRequired': 'यह फ़ील्ड आवश्यक है',
    'enterValidAmount': 'एक मान्य राशि दर्ज करें',
    'welcome': 'NestMate',
    'tagline': 'सामुदायिक जीवन को आसान बना रहे हैं।',
    'welcomeSubtitle':
        'मेंटेनेंस अब आसान है। अपने फोन पर आए वन-टाइम कोड से लॉगिन करें, या अपने बनाए हुए पासवर्ड से।',
    'getStarted': 'शुरू करें',
    'clearMonthlyBills': 'स्पष्ट मासिक बिल',
    'seeExactlyWhatYouOwe': 'देखें कि आपको कितना और क्यों देना है',
    'payInSeconds': 'सेकंडों में भुगतान करें',
    'upiPaymentUploadProof': 'UPI से एक टैप में भुगतान करें, फिर रसीद अपलोड करें।',
    'fairWaterBilling': 'निष्पक्ष पानी बिलिंग',
    'chargedByActualUsage': 'आपके इस्तेमाल के हिसाब से बिल — एक साझा उचित दर से, बराबर नहीं बांटा जाता।',

    // Authentication
    'login': 'लॉगिन',
    'signup': 'साइन अप',
    'loginWithPhone': 'फोन नंबर से लॉगिन करें',
    'loginWithPassword': 'पासवर्ड से लॉगिन करें',
    'loginWithOtp': 'OTP से लॉगिन करें',
    'signInHeading': 'साइन इन करें',
    'residentLoginSub': 'अपने बिल और सामुदायिक अपडेट देखने के लिए साइन इन करें।',
    'adminLoginSub': 'अपनी बिल्डिंग, बिलिंग और निवासियों को प्रबंधित करने के लिए साइन इन करें।',
    'phoneNumber': 'फोन नंबर',
    'enterPhoneNumber': 'कृपया अपना फोन नंबर दर्ज करें',
    'password': 'पासवर्ड',
    'enterPassword': 'कृपया अपना पासवर्ड दर्ज करें',
    'incorrectPassword': 'गलत पासवर्ड। इसके बजाय "OTP से लॉगिन करें" आज़माएं।',
    'showPassword': 'पासवर्ड दिखाएं',
    'hidePassword': 'पासवर्ड छिपाएं',
    'confirmPassword': 'पासवर्ड की पुष्टि करें',
    'flatNumber': 'फ्लैट नंबर',
    'enterFlatNumber': 'कृपया अपना फ्लैट नंबर दर्ज करें',
    'name': 'नाम',
    'enterYourName': 'अपना पूरा नाम दर्ज करें',
    'enterOtp': '6-अंकों का OTP दर्ज करें',
    'verifyPhoneNumber': 'अपना फोन नंबर सत्यापित करें',
    'otpSentMessage': 'हमने आपके फोन पर 6-अंकों का कोड भेजा है',
    'resendOtp': 'OTP फिर से भेजें',
    'resendOtpIn': 'OTP फिर से भेजें ',
    'seconds': ' सेकंड में',
    'forgotPassword': 'पासवर्ड भूल गए?',
    'passwordReset': 'पासवर्ड रीसेट',
    'createAccount': 'खाता बनाएं',
    'haveAccount': 'पहले से खाता है?',
    'noAccount': 'खाता नहीं है?',
    'agreeToTermsAndConditions': 'मैं नियम व शर्तों से सहमत हूं',
    'agreeToTerms': 'कृपया नियम और शर्तों से सहमत हों',
    'passwordMinimumLength': 'पासवर्ड कम से कम 6 अक्षरों का होना चाहिए',
    'passwordMismatch': 'पासवर्ड मेल नहीं खाते',
    'joinNestMate': 'NestMate से जुड़ें',
    'createAdminAccount': 'एडमिन खाता बनाएं',
    'adminSignupSub': 'अपना नाम, फोन नंबर और पासवर्ड सेट करें — इसके बाद आप अपनी बिल्डिंग रजिस्टर करेंगे।',
    'enterName': 'कृपया अपना नाम दर्ज करें',
    'fillDetailsBelow': 'कृपया नीचे अपना विवरण भरें',
    'enterCredentials': 'अपना फोन नंबर और पासवर्ड दर्ज करें',
    'accountCreatedSuccessfully': 'खाता सफलतापूर्वक बनाया गया!',
    'verify': 'सत्यापित करें',
    'or': 'या',

    // Common
    'save': 'सेव करें',
    'submit': 'सबमिट करें',
    'cancel': 'रद्द करें',
    'delete': 'हटाएं',
    'edit': 'संपादित करें',
    'close': 'बंद करें',
    'loading': 'लोड हो रहा है...',
    'error': 'त्रुटि',
    'success': 'सफलता',
    'warning': 'चेतावनी',
    'confirm': 'पुष्टि करें',
    'ok': 'ठीक है',
    'yes': 'हां',
    'no': 'नहीं',
    'invalidInput': 'अमान्य इनपुट। कृपया अपनी प्रविष्टियां जांचें।',
    'networkError': 'नेटवर्क त्रुटि। कृपया अपना कनेक्शन जांचें।',

    // Resident
    'resident': 'निवासी',
    'residents': 'निवासी',
    'home': 'होम',
    'residentName': 'निवासी का नाम',
    'profile': 'प्रोफ़ाइल',
    'billing': 'बिलिंग',
    'payment': 'भुगतान',
    'bills': 'बिल',
    'pastBills': 'पिछले बिल',
    'amountDue': 'देय राशि',
    'billBreakdown': 'बिल विवरण',
    'seeHowItsCalculated': 'देखें यह कैसे गणना हुआ',
    'waterUsage': 'पानी का उपयोग',
    'waterMeter': 'पानी का मीटर',
    'startReading': 'शुरुआत',
    'endReading': 'अंत',
    'usage': 'उपयोग',
    'yourUsageThisMonth': 'इस महीने आपका उपयोग',
    'viewMeterPhoto': 'मीटर फोटो देखें',
    'waterTankerShare': 'पानी टैंकर हिस्सा',
    'commonMaintenance': 'सामान्य रखरखाव',
    'subtotal': 'उप-योग',
    'downloadStatement': 'स्टेटमेंट डाउनलोड करें',
    'commonShare': 'सामान्य हिस्सा',
    'credits': 'क्रेडिट',
    'openingBalance': 'शुरुआती बकाया',
    'pay': 'अभी भुगतान करें',
    'paymentStatus': 'भुगतान स्थिति',
    'uploadScreenshot': 'स्क्रीनशॉट अपलोड करें',
    'screenshotUploaded': 'स्क्रीनशॉट अपलोड हुआ',
    'replaceScreenshotBtn': 'स्क्रीनशॉट बदलें',
    'paymentConfirmed': 'भुगतान की पुष्टि हुई',
    'paymentConfirmedByAdminLabel': 'एडमिन द्वारा भुगतान की पुष्टि की गई',
    'reportIssue': 'समस्या दर्ज करें',
    'communityNotices': 'सूचनाएं',
    'postNoticeSub': 'भवन के सभी लोगों को पोस्ट करें',
    'joinCommunity': 'कम्युनिटी से जुड़ें',
    'logout': 'लॉगआउट',
    'confirmLogout': 'क्या आप वाकई लॉगआउट करना चाहते हैं?',
    'total': 'कुल',
    'featureComingSoon': 'यह सुविधा जल्द आ रही है!',
    'paymentFeatureComingSoon': 'भुगतान सुविधाएं जल्द आ रही हैं',

    // Admin
    'admin': 'एडमिन',
    'community': 'कम्युनिटी',
    'communities': 'कम्युनिटीज़',
    'settings': 'सेटिंग्स',
    'management': 'प्रबंधन',
    'dashboard': 'डैशबोर्ड',
    'flats': 'फ्लैट्स',
    'addFlat': 'फ्लैट जोड़ें',
    'editFlat': 'फ्लैट संपादित करें',
    'flat': 'फ्लैट',
    'totalFlats': 'कुल फ्लैट्स',
    'totalResidents': 'कुल निवासी',
    'addResident': 'निवासी जोड़ें',
    'editResident': 'निवासी संपादित करें',
    'manageFlats': 'फ्लैट्स प्रबंधित करें',
    'manageResidents': 'निवासी प्रबंधित करें',
    'expenses': 'खर्चे',
    'addExpense': 'खर्च जोड़ें',
    'waterCalculation': 'पानी गणना',
    'calculateBills': 'बिल गणना करें',
    'generateBills': 'बिल तैयार करें',
    'confirmPayments': 'भुगतान की पुष्टि करें',
    'billsPending': 'बिल बकाया',
    'paymentsVerifying': 'भुगतान सत्यापित हो रहे हैं',
    'outstandingAmount': 'बकाया राशि',
    'collectionStatus': 'वसूली स्थिति',
    'paid': 'भुगतान हुआ',
    'pending': 'लंबित',
    'collected': 'एकत्रित',
    'addAdvance': 'एडवांस जोड़ें',
    'advances': 'एडवांस',

    // Units
    'rupees': '₹',
    'litres': 'ली',

    // Messages
    'successfullySaved': 'सफलतापूर्वक सेव हुआ!',
    'successfullyDeleted': 'सफलतापूर्वक हटाया गया!',
    'errorOccurred': 'एक त्रुटि हुई। कृपया फिर से प्रयास करें।',
    'phoneAlreadyExists': 'यह फोन नंबर पहले से पंजीकृत है।',
    'flatNotFound': 'फ्लैट नहीं मिला।',
    'flatPhoneMismatch':
        'यह फोन नंबर इस फ्लैट के रिकॉर्ड से मेल नहीं खाता। अपने एडमिन से संपर्क करें।',
    'adminAlreadyExists':
        'इस बिल्डिंग का एडमिन पहले से मौजूद है। उनसे अपना फ्लैट जुड़वाएं, या हैंडओवर का अनुरोध करें।',
    'phoneNotRegistered':
        'इस नंबर के लिए कोई खाता नहीं मिला। कृपया पहले साइन अप करें।',
    'invalidOtp': 'अमान्य OTP। कृपया फिर से प्रयास करें।',
    'otpSendFailed': 'OTP नहीं भेजा जा सका। कृपया फिर से प्रयास करें।',
    'otpSent': 'आपके फोन नंबर पर OTP भेजा गया।',

    // Resident shell / nav
    'navBuilding': 'बिल्डिंग',
    'navCommunity': 'सूचनाएं',
    'navProfile': 'प्रोफ़ाइल',

    // Community feed
    'committee': 'एसोसिएशन कमेटी',
    'pinned': 'पिन किया गया',
    'writeComment': 'कमेंट लिखें…',
    'comment': 'कमेंट',
    'comments': 'कमेंट्स',
    'react': 'रिएक्ट',
    'noNoticesYetTitle': 'अभी तक कोई सूचना नहीं',
    'noNoticesYetSub': 'आपके एडमिन के अपडेट यहां दिखेंगे',

    // Profile
    'yourFlat': 'आपका फ्लैट',
    'totalPaidSoFar': 'अब तक भुगतान',
    'changePhoto': 'फोटो बदलें',
    'associationRow': 'एसोसिएशन',
    'joinedTo': 'इसका हिस्सा',
    'leaveAssociation': 'एसोसिएशन छोड़ें',

    // Personal Expenses
    'myPersonalExpensesCard': 'मेरे व्यक्तिगत खर्च',
    'personalExpenses': 'व्यक्तिगत खर्च',
    'addPersonalExpense': 'खर्च जोड़ें',
    'totalSpentLabel': 'कुल खर्च',
    'spendingByCategoryLabel': 'श्रेणी के अनुसार खर्च',
    'noPersonalExpensesTitle': 'अभी तक कोई व्यक्तिगत खर्च नहीं',
    'noPersonalExpensesSub': 'अपना खुद का खर्च ट्रैक करें — बिल्डिंग के वित्त से अलग।',
    'expenseDateLabel': 'तारीख',
    'categoryFood': 'भोजन',
    'categoryTransport': 'यातायात',
    'categoryShopping': 'खरीदारी',
    'categoryBills': 'बिल',
    'categoryHealth': 'स्वास्थ्य',
    'categoryEntertainment': 'मनोरंजन',
    'categoryOther': 'अन्य',

    // Pay Now
    'payTo': 'यहां भुगतान करें',
    'copyId': 'ID कॉपी करें',
    'openUpiApp': 'UPI ऐप खोलें',
    'noUpiAppFound': 'इस डिवाइस पर कोई UPI ऐप नहीं मिला',
    'afterPayUploadScreenshot': 'भुगतान के बाद अपना स्क्रीनशॉट अपलोड करें',
    'notPaidYet': 'अभी भुगतान नहीं हुआ',

    // Report Issue
    'whatIssue': 'समस्या क्या है?',
    'issueType': 'प्रकार',
    'selectIssueType': 'एक प्रकार चुनें',
    'whereLocation': 'कहां',
    'addPhoto': 'फोटो जोड़ें',
    'takePhoto': 'फोटो खींचें',
    'chooseFromGallery': 'गैलरी से चुनें',
    'removePhoto': 'फोटो हटाएं',
    'photoPickFailed': 'कैमरा या गैलरी नहीं खुल सकी।',
    'myIssues': 'मेरी समस्याएं',
    'inProgress': 'प्रगति में',
    'resolved': 'हल हो गया',
    'issueDetails': 'समस्या का विवरण',
    'submittedOn': 'सबमिट किया गया',
    'photoAttached': 'फोटो संलग्न है',
    'issueSubmitted': 'समस्या दर्ज हो गई',

    // Admin: block setup
    'newBlockTitle': 'अपना ब्लॉक बनाएं',
    'newBlockSub':
        'पहली बार — अपने ब्लॉक का नाम रखें और तय करें कि निवासी कहां भुगतान करेंगे।',
    'blockNameLabel': 'ब्लॉक का नाम',
    'upiIdLabel': 'वसूली UPI ID',
    'yourNameInCharge': 'आपका नाम (प्रभारी)',
    'createBlockBtn': 'जारी रखें',
    'addBuildingPhoto': 'बिल्डिंग फोटो जोड़ें',
    'collectorNameLabel': 'वसूली करने वाले का नाम (भुगतान पाने वाला)',
    'waterMeteredLabel': 'यह बिल्डिंग पानी का बिल उपयोग के अनुसार करती है (मीटर्ड)',
    'committeeEnabledLabel': 'रीड-ओनली कमेटी सदस्य की अनुमति दें',
    'joinCodeLabel': 'निवासी जुड़ाव कोड',

    // Admin: add flats & residents
    'addFlatsResidents': 'फ्लैट्स और निवासी जोड़ें',
    'addPeopleSub':
        'हर फ्लैट और निवासी का फोन नंबर जोड़ें। वे उसी नंबर से लॉगिन करेंगे।',
    'residentNameLabel': 'निवासी का नाम',
    'tankerExemptLabel': 'पानी टैंकर नहीं (छूट प्राप्त)',
    'addFlatBtn': 'फ्लैट जोड़ें',
    'goToDashboard': 'डैशबोर्ड पर जाएं',
    'emptyFlatsTitle': 'अभी तक कोई फ्लैट नहीं जोड़ा गया',
    'emptyFlatsSub': 'शुरू करने के लिए अपना पहला फ्लैट जोड़ें।',
    'exemptTag': 'छूट प्राप्त',

    // Admin: join association
    'joinAssociationTitle': 'एसोसिएशन से जुड़ें',
    'joinSub':
        'क्या आपकी बिल्डिंग किसी निवासी एसोसिएशन का हिस्सा है? जुड़ने के लिए उनका दिया कोड दर्ज करें।',
    'associationCodeLabel': 'एसोसिएशन कोड',
    'joinBtn': 'एसोसिएशन से जुड़ें',
    'joinedLabel': 'जुड़ गए',
    'notJoinedLabel': 'एसोसिएशन में नहीं हैं',

    // Admin: expenses
    'monthExpenses': 'इस महीने के खर्चे',
    'emptyExpensesTitle': 'अभी तक कोई खर्च नहीं',
    'emptyExpensesSub':
        'इस महीने के खर्चे जोड़ें — टैंकर, वेतन, डीज़ल — ऐप उन्हें फ्लैट्स के बीच बांट देगा।',
    'addFirstExpense': 'पहला खर्च जोड़ें',
    'frontedBy': 'भुगतान किया',
    'recoverFrom': 'इनसे वसूल करें',
    'generateBillsBtn': 'बिल तैयार करें',

    // Admin: add expense
    'expenseNameLabel': 'यह किस लिए था',
    'categoryLabel': 'श्रेणी',
    'specifyCategoryHint': 'कृपया बताएं',
    'amountLabel': 'राशि',
    'splitAcross': 'इनमें बांटें',
    'allFlatsOption': 'सभी फ्लैट्स',
    'specificFlatsOption': 'विशिष्ट फ्लैट्स चुनें',
    'whoPaidThis': 'इसका भुगतान किसने किया?',
    'paidToCollector': 'कलेक्टर को भुगतान किया (सामान्य)',
    'residentFrontedIt': 'एक निवासी ने सीधे भुगतान किया',
    'whichFlatFronted': 'किस फ्लैट ने भुगतान किया?',
    'addReceiptOptional': 'रसीद फोटो जोड़ें (वैकल्पिक)',
    'saveExpenseBtn': 'खर्च सेव करें',
    'editExpense': 'खर्च संपादित करें',
    'updateExpenseBtn': 'खर्च अपडेट करें',
    'deleteExpenseTitle': 'खर्च हटाएं?',
    'deleteExpenseConfirm':
        'यह इस महीने के खर्चों और बिलों से हट जाएगा। इसे वापस नहीं लाया जा सकता।',

    // Admin: add advance
    'advanceReasonLabel': 'कारण',
    'advanceGivenTo': 'एडवांस किसे दिया',
    'recoverFromRows': 'इनसे वसूल करें (फ्लैट : राशि)',
    'addAnotherFlat': 'एक और फ्लैट जोड़ें',
    'saveAdvanceBtn': 'एडवांस सेव करें',

    // Admin: water calculator
    'waterCalcSub':
        'मीटर रीडिंग और खर्च दर्ज करें — ऐप उपयोग के अनुसार हर फ्लैट का हिस्सा निकालेगा।',
    'blendedRate': 'औसत दर',
    'perThousandLitres': 'प्रति 1,000 लीटर',
    'totalUsage': 'कुल उपयोग',
    'totalWaterCost': 'कुल पानी खर्च',
    'numberOfTankers': 'टैंकरों की संख्या',
    'costPerTanker': 'प्रति टैंकर खर्च',
    'meterReadingsHeader': 'मीटर रीडिंग',
    'initialReading': 'शुरुआती',
    'finalReading': 'अंतिम',
    'addToBills': 'बिलों में जोड़ें',

    // Admin: generate bills
    'previewBills': 'बिल पूर्वावलोकन',
    'totalSpend': 'कुल खर्च',
    'billsReadyCount': 'बिल तैयार',
    'sendToResidents': 'निवासियों को भेजें',
    'sendViaWhatsApp': 'WhatsApp पर भेजें',
    'whatsAppOpenFailed': 'WhatsApp नहीं खुल सका। जांचें कि यह इंस्टॉल है।',
    'sendViaSms': 'SMS से भेजें',
    'smsOpenFailed': 'मैसेज ऐप नहीं खुल सका।',
    'shareGroupSummary': 'ग्रुप के साथ महीने का सारांश साझा करें',
    'shareGroupSummarySub': 'आपके ब्लॉक के ग्रुप चैट के लिए, इस महीने के खर्चों का पूरा ब्यौरा एक ही मैसेज में।',
    'copyMessageLabel': 'मैसेज कॉपी करें',
    'copiedToClipboard': 'क्लिपबोर्ड पर कॉपी हो गया',
    'billsGeneratedLabel': 'बिल तैयार हो गए',
    'refreshBillsBtn': 'बिल रीफ़्रेश करें (नए फ्लैट जोड़े जाएंगे)',
    'billingMonthLabel': 'बिलिंग माह',
    'selectBillingMonth': 'बिलिंग माह चुनें',

    // Admin: confirm payments
    'confirmBtn': 'पुष्टि करें',
    'awaitingConfirmationLabel': 'पुष्टि का इंतज़ार',
    'confirmedTabLabel': 'पुष्टि की गई',
    'confirmedOnLabel': 'पुष्टि की गई',
    'noConfirmedPaymentsTitle': 'अभी तक कोई पुष्टि किया भुगतान नहीं',
    'noConfirmedPaymentsSub': 'इस महीने आपके पुष्टि किए भुगतान यहाँ दिखेंगे।',
    'notifications': 'सूचनाएं',
    'openIssuesLabel': 'खुली समस्याएं',
    'noNotificationsTitle': 'सब कुछ पूरा हो गया',
    'noNotificationsSub': 'अभी कोई भुगतान पुष्टि या खुली समस्या लंबित नहीं है।',
    'noPaymentsPendingTitle': 'सब कुछ पूरा हो गया',
    'noPaymentsPendingSub': 'अभी कोई भुगतान पुष्टि के इंतज़ार में नहीं है।',
    'viewScreenshotLabel': 'भुगतान स्क्रीनशॉट देखें',
    'justNow': 'अभी अभी',
    'minutesAgoSuffix': 'मिनट पहले',
    'hoursAgoSuffix': 'घंटे पहले',
    'daysAgoSuffix': 'दिन पहले',

    // Admin: flats management
    'flatsResidentsTitle': 'फ्लैट्स और निवासी',

    // Admin: transfer admin role
    'transferAdminRole': 'एडमिन की भूमिका सौंपें',
    'transferAdminTitle': 'एडमिन की भूमिका सौंपें',
    'transferAdminSub':
        'इस बिल्डिंग के लिए एक समय में केवल एक ही व्यक्ति एडमिन हो सकता है। जिसे यह भूमिका देनी है, उसका फोन नंबर डालें — सौंपते ही आप साइन आउट हो जाएंगे।',
    'newAdminPhoneLabel': 'नए एडमिन का फोन नंबर',
    'transferAdminBtn': 'एडमिन की भूमिका सौंपें',
    'transferAdminConfirmTitle': 'एडमिन की भूमिका सौंपें?',
    'transferAdminConfirmBody':
        'आपकी एडमिन एक्सेस तुरंत खत्म हो जाएगी, और यह फोन नंबर बिल्डिंग को प्रबंधित कर सकेगा। इसे यहां से वापस नहीं लिया जा सकता।',
    'transferAdminSuccess': 'एडमिन की भूमिका सौंप दी गई। साइन आउट हो रहे हैं…',

    // Misc
    'dueBy': 'देय तिथि',
    'earlierMonths': 'पिछले महीने',
    'noEarlierMonthsYet': 'अभी तक कोई पिछला महीना नहीं है — यह इस बिल्डिंग का पहला बिलिंग महीना है।',
    'continueAsCommitteeLink': 'कमेटी सदस्य के रूप में जारी रखें (रीड-ओनली)',
    'billNotReadyTitle': 'इस महीने का बिल अभी तैयार नहीं है',
    'billNotReadySub':
        'आपके एडमिन ने अभी इस महीने के बिल तैयार नहीं किए हैं। बाद में फिर देखें।',
  };

  static String get(String key, {String defaultValue = ''}) {
    return translations[key] ?? defaultValue;
  }
}
