/// Telugu localization strings for NestMate
class AppLocalizationsTe {
  static const Map<String, String> translations = {
    // Onboarding
    'language': 'భాష',
    'selectLanguage': 'భాష ఎంచుకోండి',
    'english': 'ఆంగ్లం',
    'hindi': 'హిందీ',
    'telugu': 'తెలుగు',
    'continueButton': 'కొనసాగించండి',
    'next': 'తరువాత',
    'back': 'వెనుకకు',
    'fieldRequired': 'ఈ ఫీల్డ్ తప్పనిసరి',
    'enterValidAmount': 'సరైన మొత్తాన్ని నమోదు చేయండి',
    'welcome': 'Resko',
    'tagline': 'కమ్యూనిటీ జీవితాన్ని సులభతరం చేస్తున్నాం.',
    'welcomeSubtitle':
        'మెయింటెనెన్స్ ఇప్పుడు సులభం. మీ ఫోన్‌కు వచ్చే వన్-టైమ్ కోడ్‌తో లాగిన్ అవ్వండి, లేదా మీరు సెట్ చేసుకున్న పాస్‌వర్డ్‌తో.',
    'getStarted': 'ప్రారంభించండి',
    'personalTrackerCta': 'బిల్డింగ్‌లో భాగం కాదా?',
    'personalTrackerCtaSub': 'సెటప్ వదిలేయండి — మీ వ్యక్తిగత ఖర్చులను మాత్రమే ట్రాక్ చేయండి.',
    'personalLoginHeading': 'మీ సొంత ఖర్చులను ట్రాక్ చేయండి',
    'personalLoginSub': 'బిల్డింగ్ లేదా ఫ్లాట్ అవసరం లేదు — ప్రారంభించడానికి మీ ఫోన్ నంబర్‌ని ధృవీకరించండి.',
    'continueBtn': 'కొనసాగించండి',
    'clearMonthlyBills': 'స్పష్టమైన నెలవారీ బిల్లులు',
    'seeExactlyWhatYouOwe': 'మీరు ఎంత చెల్లించాలో మరియు ఎందుకు చేయాలో చూడండి',
    'payInSeconds': 'సెకన్లలో చెల్లించండి',
    'upiPaymentUploadProof':
        'UPI ద్వారా ఒక్క టాప్‌లో చెల్లించండి, తర్వాత రసీదు అప్‌లోడ్ చేయండి.',
    'fairWaterBilling': 'న్యాయమైన నీటి బిల్లింగ్',
    'chargedByActualUsage':
        'మీరు వాడిన నీటి పరిమాణాన్ని బట్టి బిల్లు — ఒకే న్యాయమైన భాగస్వామ్య రేటుతో, అందరికీ సమానంగా పంచరు.',

    // Authentication
    'login': 'లాగిన్',
    'signup': 'సైన్ అప్',
    'loginWithPhone': 'ఫోన్ నంబర్‌తో లాగిన్ చేయండి',
    'loginWithPassword': 'పాస్‌వర్డ్‌తో లాగిన్ చేయండి',
    'loginWithOtp': 'OTP తో లాగిన్ చేయండి',
    'signInHeading': 'సైన్ ఇన్ చేయండి',
    'residentLoginSub': 'మీ బిల్లులు మరియు కమ్యూనిటీ అప్‌డేట్‌లను చూడటానికి సైన్ ఇన్ చేయండి.',
    'adminLoginSub': 'మీ భవనం, బిల్లింగ్ మరియు నివాసితులను నిర్వహించడానికి సైన్ ఇన్ చేయండి.',
    'phoneNumber': 'ఫోన్ నంబర్',
    'enterPhoneNumber': 'దయచేసి మీ ఫోన్ నంబర్‌ను నమోదు చేయండి',
    'password': 'పాస్‌వర్డ్',
    'enterPassword': 'దయచేసి మీ పాస్‌వర్డ్‌ను నమోదు చేయండి',
    'incorrectPassword': 'తప్పు పాస్‌వర్డ్. బదులుగా "OTP తో లాగిన్ చేయండి" ప్రయత్నించండి.',
    'showPassword': 'పాస్‌వర్డ్ చూపించు',
    'hidePassword': 'పాస్‌వర్డ్ దాచు',
    'confirmPassword': 'పాస్‌వర్డ్‌ను నిర్ధారించండి',
    'flatNumber': 'ఫ్లాట్ నంబర్',
    'enterFlatNumber': 'దయచేసి మీ ఫ్లాట్ నంబర్‌ను నమోదు చేయండి',
    'enterJoinCode': 'దయచేసి మీ సొసైటీ జాయిన్ కోడ్‌ను నమోదు చేయండి',
    'invalidJoinCode': 'ఈ జాయిన్ కోడ్ ఏ సొసైటీకీ సరిపోలడం లేదు',
    'name': 'పేరు',
    'enterYourName': 'మీ పూర్తి పేరు నమోదు చేయండి',
    'enterOtp': '6-అంకెల OTP ను నమోదు చేయండి',
    'verifyPhoneNumber': 'మీ ఫోన్ నంబర్‌ను ధృవీకరించండి',
    'otpSentMessage': 'మేము మీ ఫోన్‌కు 6-అంకెల కోడ్ పంపించాము',
    'resendOtp': 'OTP ను మళ్లీ పంపండి',
    'resendOtpIn': 'OTP ను మళ్లీ పంపండి ',
    'seconds': ' సెకన్ల్లో',
    'forgotPassword': 'పాస్‌వర్డ్‌ను మర్చిపోయారా?',
    'passwordReset': 'పాస్‌వర్డ్ రీసెట్',
    'createAccount': 'ఖాతా సృష్టించండి',
    'haveAccount': 'ఇప్పటికే ఖాతా ఉందా?',
    'noAccount': 'ఖాతా లేనా?',
    'agreeToTermsAndConditions': 'నేను నిబంధనలకు సమ్మతిని పూరిస్తున్నాను',
    'agreeToTerms': 'దయచేసి నిబంధనలకు సమ్మతిని పూరించండి',
    'passwordMinimumLength': 'పాస్‌వర్డ్ కనీసం 6 అక్షరాలు ఉండాలి',
    'passwordMismatch': 'పాస్‌వర్డ్‌లు సరిపోలడం లేదు',
    'joinNestMate': 'Resko కు చేరండి',
    'createAdminAccount': 'అడ్మిన్ ఖాతా సృష్టించండి',
    'adminSignupSub': 'మీ పేరు, ఫోన్ నంబర్ మరియు పాస్‌వర్డ్ సెట్ చేయండి — తర్వాత మీరు మీ భవనాన్ని నమోదు చేస్తారు.',
    'enterName': 'దయచేసి మీ పేరు నమోదు చేయండి',
    'fillDetailsBelow': 'దయచేసి దిగువ వివరాలను నమోదు చేయండి',
    'enterCredentials': 'మీ ఫోన్ నంబర్ మరియు పాస్‌వర్డ్ నమోదు చేయండి',
    'accountCreatedSuccessfully': 'ఖాతా విజయవంతంగా సృష్టించబడింది!',
    'verify': 'ధృవీకరించండి',
    'or': 'లేదా',

    // Common
    'save': 'సేవ్ చేయండి',
    'submit': 'సమర్పించండి',
    'cancel': 'రద్దు చేయండి',
    'delete': 'తొలగించండి',
    'edit': 'సవరించండి',
    'close': 'మూయండి',
    'loading': 'లోడ్ చేస్తోంది...',
    'error': 'లోపం',
    'success': 'విజయం',
    'warning': 'హెచ్చరిక',
    'confirm': 'నిర్ధారించండి',
    'ok': 'సరే',
    'yes': 'అవును',
    'no': 'కాదు',
    'invalidInput': 'చెల్లని ఇన్‌పుట్. దయచేసి మీ ఎంట్రీలను తనిఖీ చేయండి.',
    'networkError': 'నెట్‌వర్క్ లోపం. దయచేసి మీ కనెక్షన్‌ను తనిఖీ చేయండి.',

    // Resident
    'resident': 'నివాసి',
    'residents': 'నివాసులు',
    'home': 'హోమ్',
    'residentName': 'నివాసి పేరు',
    'profile': 'ప్రొఫైల్',
    'billing': 'బిల్లింగ్',
    'payment': 'చెల్లింపు',
    'bills': 'బిల్లులు',
    'pastBills': 'గత బిల్లులు',
    'amountDue': 'చెల్లింపు చేయవలసిన మొత్తం',
    'creditBalanceLabel': 'మీకు చెల్లించబడుతుంది',
    'creditContactAdminMessage':
        'ఇది మీకు అడ్మిన్ ద్వారా చెల్లించబడుతుంది. దయచేసి అడ్మిన్‌ను సంప్రదించండి.',
    'billBreakdown': 'బిల్ల్ విభజన',
    'seeHowItsCalculated': 'ఇది ఎలా లెక్కించబడిందో చూడండి',
    'waterUsage': 'నీటి వినియోగం',
    'waterMeter': 'నీటి మీటర్',
    'startReading': 'ప్రారంభ',
    'endReading': 'ముగింపు',
    'usage': 'వినియోగం',
    'yourUsageThisMonth': 'ఈ నెలలో మీ వినియోగం',
    'viewMeterPhoto': 'మీటర్ ఫోటో చూడండి',
    'noMeterPhotoYet': 'ఈ నెలకు ఇంకా మీటర్ ఫోటో జోడించలేదు.',
    'waterTankerShare': 'నీటి ట్యాంకర్ వాటా',
    'commonMaintenance': 'సామాన్య నిర్వహణ',
    'subtotal': 'ఉప మొత్తం',
    'downloadStatement': 'స్టేట్‌మెంట్ డౌన్‌లోడ్ చేయండి',
    'statementFailed': 'స్టేట్‌మెంట్ సృష్టించలేకపోయాము. దయచేసి మళ్లీ ప్రయత్నించండి.',
    'statementSaved': 'స్టేట్‌మెంట్ సేవ్ చేయబడింది.',
    'shareStatement': 'స్టేట్‌మెంట్ షేర్ చేయండి',
    'commonShare': 'సామాన్య వాటా',
    'credits': 'క్రెడిట్‌లు',
    'openingBalance': 'ప్రారంభ సంతులనం',
    'pay': 'చెల్లించండి',
    'paymentStatus': 'చెల్లింపు స్థితి',
    'uploadScreenshot': 'స్క్రీన్‌షాట్ అప్‌లోడ్ చేయండి',
    'screenshotUploaded': 'స్క్రీన్‌షాట్ అప్‌లోడ్ చేయబడింది',
    'replaceScreenshotBtn': 'స్క్రీన్‌షాట్ మార్చండి',
    'paymentConfirmed': 'చెల్లింపు ఆమోదించబడింది',
    'paymentConfirmedByAdminLabel': 'అడ్మిన్ ద్వారా చెల్లింపు నిర్ధారించబడింది',
    'reportIssue': 'సమస్యను నివేదించండి',
    'communityNotices': 'నోటీసులు',
    'postNoticeSub': 'భవనంలో అందరికీ పోస్ట్ చేయండి',
    'joinCommunity': 'కమ్యూనిటీ చేరండి',
    'logout': 'లాగ్‌అవుట్',
    'confirmLogout': 'మీరు నిజంగా లాగ్‌అవుట్ చేయాలనుకుంటున్నారా?',
    'total': 'మొత్తం',
    'featureComingSoon': 'ఈ ఫీచర్ త్వరలో వస్తుంది!',
    'paymentFeatureComingSoon': 'చెల్లింపు ఫీచర్‌లు త్వరలో వస్తాయి',

    // Admin
    'admin': 'నిర్వాహకుడు',
    'community': 'కమ్యూనిటీ',
    'communities': 'కమ్యూనిటీలు',
    'settings': 'సెట్టింగ్‌లు',
    'management': 'నిర్వహణ',
    'dashboard': 'డ్యాష్‌బోర్డ్',
    'flats': 'ఫ్లాట్‌లు',
    'addFlat': 'ఫ్లాట్ జోడించండి',
    'editFlat': 'ఫ్లాట్‌ను సవరించండి',
    'flat': 'ఫ్లాట్',
    'totalFlats': 'మొత్తం ఫ్లాట్‌లు',
    'totalResidents': 'మొత్తం నివాసులు',
    'addResident': 'నివాసిని జోడించండి',
    'editResident': 'నివాసిని సవరించండి',
    'manageFlats': 'ఫ్లాట్‌లను నిర్వహించండి',
    'manageResidents': 'నివాసులను నిర్వహించండి',
    'expenses': 'ఖర్చులు',
    'addExpense': 'ఖర్చు జోడించండి',
    'waterCalculation': 'నీటి గణన',
    'calculateBills': 'బిల్లులను లెక్కించండి',
    'generateBills': 'బిల్లులను రూపొందించండి',
    'confirmPayments': 'చెల్లింపులను నిర్ధారించండి',
    'billsPending': 'బిల్లులు పెండింగ్‌లో ఉన్నాయి',
    'paymentsVerifying': 'చెల్లింపులను ధృవీకరించడం',
    'outstandingAmount': 'అత్యంత మొత్తం',
    'collectionStatus': 'సংగ్రహ స్థితి',
    'paid': 'చెల్లించారు',
    'pending': 'పెండింగ్‌లో ఉంది',
    'collected': 'సేకరించారు',
    'addAdvance': 'ముందస్తు జోడించండి',
    'advances': 'ముందస్తులు',

    // Units
    'rupees': '₹',
    'litres': 'L',

    // Messages
    'successfullySaved': 'విజయవంతంగా సేవ్ చేయబడింది!',
    'successfullyDeleted': 'విజయవంతంగా తొలగించబడింది!',
    'errorOccurred': 'లోపం సంభవించింది. దయచేసి మళ్లీ ప్రయత్నించండి.',
    'phoneAlreadyExists': 'ఈ ఫోన్ నంబర్ ఇప్పటికే నమోదు చేయబడింది.',
    'flatNotFound': 'ఫ్లాట్ కనుగొనబడలేదు.',
    'flatPhoneMismatch':
        'ఈ ఫోన్ నంబర్ ఈ ఫ్లాట్ రికార్డులతో సరిపోలడం లేదు. మీ అడ్మిన్‌ను సంప్రదించండి.',
    'adminAlreadyExists':
        'ఈ భవనానికి ఇప్పటికే ఒక అడ్మిన్ ఉన్నారు. మిమ్మల్ని ఒక ఫ్లాట్‌గా చేర్చమని వారిని అడగండి, లేదా హ్యాండ్‌ఓవర్ కోరండి.',
    'adminNoSocietyYet':
        'ఈ నంబర్‌కు ఇంకా ఏ సొసైటీ నమోదు కాలేదు. మీ సొసైటీని ఏర్పాటు చేసుకోవడానికి క్రింద Create Account నొక్కండి.',
    'phoneNotRegistered':
        'ఈ నంబర్ కోసం ఖాతా కనుగొనబడలేదు. దయచేసి ముందుగా సైన్ అప్ చేయండి.',
    'invalidOtp': 'చెల్లని OTP. దయచేసి మళ్లీ ప్రయత్నించండి.',
    'otpSendFailed': 'OTP పంపడం సాధ్యం కాలేదు. దయచేసి మళ్లీ ప్రయత్నించండి.',
    'otpSent': 'మీ ఫోన్ నంబర్‌కు OTP పంపబడింది.',

    // Resident shell / nav
    'navBuilding': 'భవనం',
    'navCommunity': 'నోటీసులు',
    'navMyExpenses': 'నా ఖర్చులు',
    'navProfile': 'ప్రొఫైల్',

    // Community feed
    'committee': 'అసోసియేషన్ కమిటీ',
    'pinned': 'పిన్ చేయబడింది',
    'writeComment': 'కామెంట్ రాయండి…',
    'comment': 'కామెంట్',
    'comments': 'కామెంట్‌లు',
    'react': 'రియాక్ట్',
    'noNoticesYetTitle': 'ఇంకా నోటీసులు లేవు',
    'noNoticesYetSub': 'మీ అడ్మిన్ అప్‌డేట్‌లు ఇక్కడ కనిపిస్తాయి',

    // Profile
    'yourFlat': 'మీ ఫ్లాట్',
    'totalPaidSoFar': 'ఇప్పటివరకు చెల్లించింది',
    'changePhoto': 'ఫోటో మార్చండి',
    'associationRow': 'అసోసియేషన్',
    'joinedTo': 'భాగం',
    'leaveAssociation': 'అసోసియేషన్ నుండి వైదొలగండి',

    // Building Expenses (resident, read-only)
    'buildingExpensesTitle': 'భవన ఖర్చులు',
    'commonPoolTotalLabel': 'మొత్తం కామన్ పూల్',
    'noExpensesYetTitle': 'ఇంకా ఖర్చులు లేవు',
    'noExpensesYetSub': 'మీ అడ్మిన్ ఈ నెలకు ఇంకా ఖర్చులు నమోదు చేయలేదు.',

    // Personal Expenses
    'myPersonalExpensesCard': 'నా వ్యక్తిగత ఖర్చులు',
    'personalExpenses': 'వ్యక్తిగత ఖర్చులు',
    'addPersonalExpense': 'ఖర్చు జోడించండి',
    'editPersonalExpense': 'ఖర్చు మార్చండి',
    'totalSpentLabel': 'మొత్తం ఖర్చు',
    'spendingByCategoryLabel': 'వర్గం వారీగా ఖర్చు',
    'monthlySalaryLabel': 'నెలవారీ జీతం',
    'addSalaryBtn': 'జోడించు',
    'editBtn': 'మార్చు',
    'setSalaryTitle': 'మీ నెలవారీ జీతాన్ని నమోదు చేయండి',
    'saveBtn': 'సేవ్ చేయండి',
    'remainingBalanceLabel': 'మిగిలింది',
    'overspentLabel': 'అధిక ఖర్చు',
    'monthlyBudgetsLabel': 'నెలవారీ బడ్జెట్‌లు',
    'monthlyBudgetsSub': 'ప్రతి వర్గానికి ఖర్చు పరిమితిని పెట్టండి — సెట్ చేయడానికి లేదా మార్చడానికి నొక్కండి.',
    'setBudgetTitle': 'బడ్జెట్ పెట్టండి',
    'monthlyBudgetHint': 'నెలవారీ పరిమితి',
    'setBudgetBtn': 'బడ్జెట్ పెట్టండి',
    'noPersonalExpensesTitle': 'ఇంకా వ్యక్తిగత ఖర్చులు లేవు',
    'noPersonalExpensesSub': 'మీ సొంత ఖర్చులను ట్రాక్ చేయండి — భవనం ఆర్థిక వ్యవహారాల నుండి వేరుగా.',
    'changeReasonLabel': 'దీన్ని ఎందుకు మారుస్తున్నారు?',
    'changeReasonHint': 'దీనికి నివాసులు చెల్లిస్తున్నారు, కాబట్టి ఏమి ఎందుకు మారిందో వారికి తెలియజేయబడుతుంది.',
    'changeReasonRequired': 'దయచేసి ఈ మార్పుకు కారణం తెలపండి',
    'changeHistoryLabel': 'మార్పుల చరిత్ర',
    'changedOnLabel': 'మార్చబడింది',
    'expenseDateLabel': 'తేదీ',
    'categoryFood': 'ఆహారం',
    'categoryTransport': 'రవాణా',
    'categoryShopping': 'షాపింగ్',
    'categoryBills': 'బిల్లులు',
    'categoryHealth': 'ఆరోగ్యం',
    'categoryEntertainment': 'వినోదం',
    'categoryOther': 'ఇతర',

    // Pay Now
    'payTo': 'చెల్లించండి',
    'copyId': 'ID కాపీ చేయండి',
    'openUpiApp': 'UPI యాప్ తెరవండి',
    'noUpiAppFound': 'ఈ పరికరంలో UPI యాప్ కనుగొనబడలేదు',
    'afterPayUploadScreenshot': 'చెల్లించాక స్క్రీన్‌షాట్ అప్‌లోడ్ చేయండి',
    'notPaidYet': 'ఇంకా చెల్లించలేదు',

    // Report Issue
    'whatIssue': 'సమస్య ఏమిటి?',
    'issueType': 'రకం',
    'selectIssueType': 'ఒక రకాన్ని ఎంచుకోండి',
    'whereLocation': 'ఎక్కడ',
    'addPhoto': 'ఫోటో జోడించండి',
    'takePhoto': 'ఫోటో తీయండి',
    'chooseFromGallery': 'గ్యాలరీ నుండి ఎంచుకోండి',
    'removePhoto': 'ఫోటో తీసివేయండి',
    'photoPickFailed': 'కెమెరా లేదా గ్యాలరీ తెరవలేకపోయాం.',
    'myIssues': 'నా సమస్యలు',
    'inProgress': 'పరిష్కారంలో ఉంది',
    'resolved': 'పరిష్కరించబడింది',
    'issueDetails': 'సమస్య వివరాలు',
    'submittedOn': 'సమర్పించిన తేదీ',
    'photoAttached': 'ఫోటో జోడించబడింది',
    'issueSubmitted': 'సమస్య సమర్పించబడింది',

    // Admin: block setup
    'newBlockTitle': 'మీ బ్లాక్ సృష్టించండి',
    'newBlockSub':
        'మొదటిసారి — మీ బ్లాక్‌కు పేరు పెట్టి, నివాసితులు చెల్లించే చోటును సెట్ చేయండి.',
    'blockNameLabel': 'బ్లాక్ పేరు',
    'upiIdLabel': 'వసూలు UPI ID',
    'yourNameInCharge': 'మీ పేరు (ఇన్‌చార్జ్)',
    'createBlockBtn': 'కొనసాగించండి',
    'addBuildingPhoto': 'భవనం ఫోటో జోడించండి',
    'collectorNameLabel': 'వసూలు చేసేవారి పేరు (చెల్లింపులు అందుకునేవారు)',
    'waterMeteredLabel': 'ఈ భవనం నీటిని వాడకం ప్రకారం బిల్లు చేస్తుంది (మీటర్డ్)',
    'committeeEnabledLabel': 'రీడ్-ఓన్లీ కమిటీ సభ్యుడిని అనుమతించండి',
    'joinCodeLabel': 'నివాసి చేరిక కోడ్',
    'societyReadyTitle': 'మీ సొసైటీ సిద్ధంగా ఉంది',
    'societyReadySub':
        'ఈ కోడ్‌ను మీ నివాసులకు పంపండి. సైన్ అప్ చేసేటప్పుడు వారు దీన్నే నమోదు చేస్తారు — చేరడానికి ఇదే ఏకైక మార్గం.',
    'shareWithResidents': 'నివాసులకు పంపండి',
    'joinCodeCopied': 'చేరిక కోడ్ కాపీ అయింది',
    'joinCodeShareMessage':
        'Resko లో మా సొసైటీలో చేరండి.\n\nచేరిక కోడ్: %s\n\nయాప్ డౌన్‌లోడ్ చేసి, Sign Up నొక్కి, మీ ఫ్లాట్ నంబర్‌తో పాటు ఈ కోడ్ నమోదు చేయండి.',
    'duplicateSocietyTitle': 'ఈ పేరుతో సొసైటీ ఇప్పటికే ఉంది',
    'duplicateSocietyBody':
        'మీ భవనం నుండి ఎవరైనా ఇప్పటికే దీన్ని ఏర్పాటు చేసి ఉంటే, వారి నుండి చేరిక కోడ్ తీసుకుని నివాసిగా సైన్ అప్ చేయండి. రెండో సొసైటీ సృష్టిస్తే మీ నివాసులు రెండు వేర్వేరు భవనాలుగా విడిపోతారు.',
    'createAnyway': 'అయినా సృష్టించండి',
    'goBack': 'వెనక్కి వెళ్లండి',

    // Admin: add flats & residents
    'addFlatsResidents': 'ఫ్లాట్‌లు & నివాసితులు జోడించండి',
    'addPeopleSub':
        'ప్రతి ఫ్లాట్‌ని, నివాసి ఫోన్ నంబర్‌ని జోడించండి. వారు ఆ నంబర్‌తో లాగిన్ అవుతారు.',
    'residentNameLabel': 'నివాసి పేరు',
    'tankerExemptLabel': 'నీటి ట్యాంకర్ లేదు (మినహాయింపు)',
    'addFlatBtn': 'ఫ్లాట్ జోడించండి',
    'goToDashboard': 'డాష్‌బోర్డ్‌కి వెళ్ళండి',
    'emptyFlatsTitle': 'ఇంకా ఫ్లాట్‌లు జోడించలేదు',
    'emptyFlatsSub': 'ప్రారంభించడానికి మీ మొదటి ఫ్లాట్‌ని జోడించండి.',
    'exemptTag': 'మినహాయింపు',

    // Admin: join association
    'joinAssociationTitle': 'అసోసియేషన్‌లో చేరండి',
    'joinSub':
        'మీ భవనం నివాసితుల అసోసియేషన్‌లో భాగమా? కనెక్ట్ చేయడానికి వారు షేర్ చేసిన కోడ్‌ని నమోదు చేయండి.',
    'associationCodeLabel': 'అసోసియేషన్ కోడ్',
    'joinBtn': 'అసోసియేషన్‌లో చేరండి',
    'joinedLabel': 'చేరారు',
    'notJoinedLabel': 'అసోసియేషన్‌లో లేరు',

    // Admin: expenses
    'monthExpenses': 'ఈ నెల ఖర్చులు',
    'emptyExpensesTitle': 'ఇంకా ఖర్చులు లేవు',
    'emptyExpensesSub':
        'ఈ నెల ఖర్చులు జోడించండి — ట్యాంకర్, జీతం, డీజిల్ — యాప్ వాటిని ఫ్లాట్‌ల మధ్య పంచుతుంది.',
    'addFirstExpense': 'మొదటి ఖర్చు జోడించండి',
    'frontedBy': 'చెల్లించినవారు',
    'recoverFrom': 'వీరి నుండి వసూలు చేయాలి',
    'generateBillsBtn': 'బిల్లులు తయారు చేయండి',

    // Admin: add expense
    'expenseNameLabel': 'దేని కోసం',
    'categoryLabel': 'వర్గం',
    'specifyCategoryHint': 'దయచేసి తెలియజేయండి',
    'amountLabel': 'మొత్తం',
    'splitAcross': 'వీటి మధ్య పంచండి',
    'allFlatsOption': 'అన్ని ఫ్లాట్‌లు',
    'specificFlatsOption': 'నిర్దిష్ట ఫ్లాట్‌లను ఎంచుకోండి',
    'whoPaidThis': 'దీన్ని ఎవరు చెల్లించారు?',
    'paidToCollector': 'కలెక్టర్‌కి చెల్లించారు (సాధారణం)',
    'residentFrontedIt': 'ఒక నివాసి నేరుగా చెల్లించారు',
    'whichFlatFronted': 'ఏ ఫ్లాట్ చెల్లించింది?',
    'addReceiptOptional': 'రసీదు ఫోటో జోడించండి (ఐచ్ఛికం)',
    'saveExpenseBtn': 'ఖర్చును సేవ్ చేయండి',
    'editExpense': 'ఖర్చును సవరించండి',
    'updateExpenseBtn': 'ఖర్చును అప్‌డేట్ చేయండి',
    'deleteExpenseTitle': 'ఖర్చును తొలగించాలా?',
    'deleteExpenseConfirm':
        'ఇది ఈ నెల ఖర్చులు మరియు బిల్లుల నుండి తీసివేయబడుతుంది. దీన్ని వెనక్కి తీసుకోలేరు.',
    'howFundedLabel': 'దీనికి డబ్బు ఎక్కడ నుండి వస్తుంది?',
    'splitAcrossResidentsOption': 'ఈ నెల నివాసితులలో పంచండి',
    'payFromReserveOption': 'రిజర్వ్ ఫండ్ నుండి చెల్లించండి',
    'reserveFundBalance': 'రిజర్వ్ ఫండ్ బ్యాలెన్స్',
    'insufficientReserveError': 'ఇది రిజర్వ్ ఫండ్ ప్రస్తుత బ్యాలెన్స్ కంటే ఎక్కువ.',

    // Admin: reserve fund
    'reserveFundLabel': 'రిజర్వ్ ఫండ్',
    'addToReserveFund': 'రిజర్వ్ ఫండ్‌కు జోడించండి',
    'whoIsPayingLabel': 'ఎవరు చెల్లిస్తున్నారు?',
    'whoHasPaidLabel': 'ఎవరు చెల్లించారు',
    'noContributionsYet': 'ఇంకా ఏ చెల్లింపూ నమోదు కాలేదు.',
    'reserveCollectedLabel': 'వసూలైనది',
    'reserveSpentLabel': 'ఖర్చైనది',
    'removeContributionTitle': 'ఈ చెల్లింపును తొలగించాలా?',
    'removeContributionBody': 'రిజర్వ్ ఫండ్ నిల్వ ఈ మొత్తం మేర తగ్గుతుంది.',
    'selectAll': 'అన్నీ ఎంచుకోండి',
    'clearAll': 'అన్నీ తీసివేయండి',
    'remove': 'తొలగించు',
    'currentReserveBalance': 'ప్రస్తుత రిజర్వ్ బ్యాలెన్స్',
    'reserveFundAmountPerFlatLabel': 'ప్రతి ఫ్లాట్‌కు మొత్తం',
    'saveReserveFundBtn': 'రిజర్వ్‌కు జోడించండి',
    'paidFromReserveBadge': 'రిజర్వ్ ఫండ్ నుండి చెల్లించబడింది',

    // Admin: work list
    'workListTitle': 'పని జాబితా',
    'addWorkItemTitle': 'పని జోడించండి',
    'workItemTitleHint': 'ఏమి చేయాలి?',
    'workItemDescriptionHint': 'వివరణ (ఐచ్ఛికం)',
    'addWorkItemBtn': 'జోడించు',
    'noWorkItemsTitle': 'ఇంకా పనులు లేవు',
    'noWorkItemsSub': 'ఏదైనా చేయాల్సి ఉంటే + నొక్కండి.',
    'deleteWorkItemTitle': 'ఈ పనిని తొలగించాలా?',

    // Admin: add advance
    'advanceReasonLabel': 'కారణం',
    'advanceGivenTo': 'అడ్వాన్స్ ఇవ్వబడింది',
    'recoverFromRows': 'వసూలు చేయాలి (ఫ్లాట్ : మొత్తం)',
    'addAnotherFlat': 'మరో ఫ్లాట్ జోడించండి',
    'saveAdvanceBtn': 'అడ్వాన్స్ సేవ్ చేయండి',

    // Admin: water calculator
    'waterCalcSub':
        'మీటర్ రీడింగ్‌లు & ఖర్చులు నమోదు చేయండి — వాడకం ప్రకారం ప్రతి ఫ్లాట్ వాటాను యాప్ లెక్కిస్తుంది.',
    'blendedRate': 'సగటు రేటు',
    'perThousandLitres': 'ప్రతి 1,000 లీటర్లకు',
    'totalUsage': 'మొత్తం వాడకం',
    'totalWaterCost': 'మొత్తం నీటి ఖర్చు',
    'numberOfTankers': 'ట్యాంకర్ల సంఖ్య',
    'costPerTanker': 'ఒక్కో ట్యాంకర్ ఖర్చు',
    'meterReadingsHeader': 'మీటర్ రీడింగ్‌లు',
    'initialReading': 'ప్రారంభం',
    'finalReading': 'చివరి',
    'addToBills': 'బిల్లులకు జోడించండి',

    // Admin: generate bills
    'previewBills': 'బిల్లుల ప్రివ్యూ',
    'totalSpend': 'మొత్తం ఖర్చు',
    'billsReadyCount': 'బిల్లులు సిద్ధం',
    'sendToResidents': 'నివాసితులకు పంపండి',
    'sendViaWhatsApp': 'WhatsApp ద్వారా పంపండి',
    'whatsAppOpenFailed': 'WhatsApp తెరవలేకపోయాం. అది ఇన్‌స్టాల్ అయిందో లేదో చూడండి.',
    'sendViaSms': 'SMS ద్వారా పంపండి',
    'smsOpenFailed': 'మెసేజ్ యాప్ తెరవలేకపోయాం.',
    'shareGroupSummary': 'గ్రూప్‌తో నెల సారాంశం పంచుకోండి',
    'shareGroupSummarySub': 'మీ బ్లాక్ గ్రూప్ చాట్ కోసం, ఈ నెల ఖర్చుల పూర్తి వివరణ ఒకే మెసేజ్‌లో.',
    'copyMessageLabel': 'మెసేజ్ కాపీ చేయండి',
    'copiedToClipboard': 'క్లిప్‌బోర్డ్‌కు కాపీ అయింది',
    'billsGeneratedLabel': 'బిల్లులు సిద్ధమయ్యాయి',
    'refreshBillsBtn': 'బిల్లులు రిఫ్రెష్ చేయండి (కొత్త ఫ్లాట్లు జోడించబడతాయి)',
    'billingMonthLabel': 'బిల్లింగ్ నెల',
    'selectBillingMonth': 'బిల్లింగ్ నెలను ఎంచుకోండి',

    // Admin: confirm payments
    'confirmBtn': 'నిర్ధారించండి',
    'awaitingConfirmationLabel': 'నిర్ధారణ కోసం వేచి ఉంది',
    'confirmedTabLabel': 'నిర్ధారించబడింది',
    'confirmedOnLabel': 'నిర్ధారించబడింది',
    'noConfirmedPaymentsTitle': 'ఇంకా నిర్ధారించిన చెల్లింపులు లేవు',
    'noConfirmedPaymentsSub': 'ఈ నెల మీరు నిర్ధారించిన చెల్లింపులు ఇక్కడ కనిపిస్తాయి.',
    'notifications': 'నోటిఫికేషన్లు',
    'openIssuesLabel': 'తెరిచి ఉన్న సమస్యలు',
    'noNotificationsTitle': 'మీరు అన్నీ పూర్తి చేశారు',
    'noNotificationsSub': 'ప్రస్తుతం చెల్లింపు నిర్ధారణలు లేదా తెరిచి ఉన్న సమస్యలు లేవు.',
    'noPaymentsPendingTitle': 'మీరు అన్నీ పూర్తి చేశారు',
    'noPaymentsPendingSub': 'ప్రస్తుతం నిర్ధారణ కోసం ఏ చెల్లింపులు వేచి లేవు.',
    'viewScreenshotLabel': 'చెల్లింపు స్క్రీన్‌షాట్ చూడండి',
    'justNow': 'ఇప్పుడే',
    'minutesAgoSuffix': 'నిమిషాల క్రితం',
    'hoursAgoSuffix': 'గంటల క్రితం',
    'daysAgoSuffix': 'రోజుల క్రితం',

    // Admin: flats management
    'flatsResidentsTitle': 'ఫ్లాట్‌లు & నివాసితులు',

    // Admin: transfer admin role
    'transferAdminRole': 'అడ్మిన్ బాధ్యతను అప్పగించండి',
    'transferAdminTitle': 'అడ్మిన్ బాధ్యతను అప్పగించండి',
    'transferAdminSub':
        'ఈ భవనానికి ఒక సమయంలో ఒక్కరే అడ్మిన్‌గా ఉండగలరు. బాధ్యత తీసుకోవాల్సిన వ్యక్తి ఫోన్ నంబర్ నమోదు చేయండి — అప్పగించిన వెంటనే మీరు సైన్ అవుట్ అవుతారు.',
    'newAdminPhoneLabel': 'కొత్త అడ్మిన్ ఫోన్ నంబర్',
    'transferAdminBtn': 'అడ్మిన్ బాధ్యతను అప్పగించండి',
    'transferAdminConfirmTitle': 'అడ్మిన్ బాధ్యతను అప్పగించాలా?',
    'transferAdminConfirmBody':
        'మీ అడ్మిన్ యాక్సెస్ వెంటనే పోతుంది, మరియు ఈ ఫోన్ నంబర్ భవనాన్ని నిర్వహించగలదు. దీన్ని ఇక్కడి నుండి వెనక్కి తీసుకోలేరు.',
    'transferAdminSuccess': 'అడ్మిన్ బాధ్యత అప్పగించబడింది. సైన్ అవుట్ చేస్తున్నాం…',

    // Misc
    'dueBy': 'గడువు',
    'earlierMonths': 'గత నెలలు',
    'noEarlierMonthsYet': 'ఇంకా గత నెలలు లేవు — ఇది ఈ భవనానికి మొదటి బిల్లింగ్ నెల.',
    'continueAsCommitteeLink': 'కమిటీ సభ్యుడిగా కొనసాగించండి (రీడ్-ఓన్లీ)',
    'billNotReadyTitle': 'ఈ నెల బిల్లు ఇంకా సిద్ధంగా లేదు',
    'billNotReadySub': 'మీ అడ్మిన్ ఇంకా ఈ నెల బిల్లులు తయారు చేయలేదు. తర్వాత మళ్లీ చూడండి.',
  };

  static String get(String key, {String defaultValue = ''}) {
    return translations[key] ?? defaultValue;
  }
}
